# Generated by Django 4.1.7 on 2023-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('is_authorised', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=6)),
                ('characteristics', models.TextField(max_length=500)),
                ('links', models.TextField(max_length=200)),
            ],
        ),
    ]
