# Generated by Django 4.1.7 on 2023-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catitem',
            name='characteristics_long',
            field=models.TextField(default='text', max_length=1000),
            preserve_default=False,
        ),
    ]
