# Generated by Django 4.1.7 on 2023-03-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_catitem_characteristics_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_authorised',
        ),
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='FavItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favd', models.BooleanField(default=False)),
                ('acpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpha.account')),
                ('itpk', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alpha.catitem')),
            ],
        ),
    ]
